export const SWEDISH_PATTERNS = {
  personnummer:
    /\b(?:19|20)?\d{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\d|3[01])[-+]\d{4}\b/g,
  samordningsnummer:
    /\b(?:19|20)?\d{2}(?:0[1-9]|1[0-2])(?:6[1-9]|[7-8]\d|9[01])[-+]\d{4}\b/g,
  phone:
    /(?<!\w)(?:(?:\+46|0046|0)\s?[-\s]?\d{1,3}(?:[-\s]?\d{2,4}){2,4})(?!\w)/g,
  email: /\b[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}\b/g,
} as const;

export const COMMON_SWEDISH_NAMES_MASCULINE = [
  "Adam",
  "Alexander",
  "Alfred",
  "Anders",
  "Andreas",
  "Anton",
  "Axel",
  "Benjamin",
  "Björn",
  "Carl",
  "Christian",
  "Christoffer",
  "Daniel",
  "David",
  "Edvin",
  "Elias",
  "Emil",
  "Erik",
  "Felix",
  "Filip",
  "Fredrik",
  "Gabriel",
  "Gustav",
  "Hampus",
  "Harald",
  "Henrik",
  "Hugo",
  "Jakob",
  "Johan",
  "Johannes",
  "Jonas",
  "Jonathan",
  "Josef",
  "Karl",
  "Lars",
  "Leo",
  "Liam",
  "Linus",
  "Ludvig",
  "Lucas",
  "Magnus",
  "Marcus",
  "Martin",
  "Mattias",
  "Max",
  "Mikael",
  "Nils",
  "Noah",
  "Olof",
  "Oscar",
  "Otto",
  "Per",
  "Peter",
  "Pontus",
  "Rasmus",
  "Robert",
  "Robin",
  "Samuel",
  "Sebastian",
  "Simon",
  "Stefan",
  "Sven",
  "Theo",
  "Thomas",
  "Tobias",
  "Viktor",
  "Vilhelm",
  "William",
  "Åke",
] as const;

export const COMMON_SWEDISH_NAMES_FEMININE = [
  "Agnes",
  "Alice",
  "Alicia",
  "Alva",
  "Amanda",
  "Amelie",
  "Amy",
  "Astrid",
  "Britta",
  "Carin",
  "Carolina",
  "Christina",
  "Clara",
  "Ebba",
  "Elin",
  "Elisa",
  "Elisabet",
  "Ella",
  "Ellen",
  "Elsa",
  "Emma",
  "Emilia",
  "Ester",
  "Eva",
  "Felicia",
  "Frida",
  "Hanna",
  "Helena",
  "Ida",
  "Ingrid",
  "Isabella",
  "Jenny",
  "Jessica",
  "Julia",
  "Karin",
  "Katarina",
  "Klara",
  "Kristina",
  "Laura",
  "Lena",
  "Lina",
  "Linda",
  "Lisa",
  "Lotta",
  "Louise",
  "Maja",
  "Maria",
  "Malin",
  "Matilda",
  "Mia",
  "Moa",
  "Nora",
  "Olivia",
  "Petra",
  "Saga",
  "Sara",
  "Selma",
  "Sigrid",
  "Signe",
  "Sofia",
  "Sophia",
  "Stella",
  "Stina",
  "Tilda",
  "Vera",
  "Victoria",
  "Åsa",
  "Åse",
] as const;

export const COMMON_SWEDISH_NAMES_NEUTRAL = [
  "Alex",
  "Charlie",
  "Elliot",
  "Kim",
  "Linn",
  "Love",
  "Morgan",
  "Nico",
  "Nova",
  "Robin",
  "Rut",
  "Sam",
  "Skye",
] as const;

export const COMMON_MULTICULTURAL_NAMES_ARABIC = [
  "Aisha",
  "Ali",
  "Amir",
  "Amina",
  "Fatima",
  "Hassan",
  "Layla",
  "Mariam",
  "Mohamed",
  "Mohammad",
  "Mohammed",
  "Nour",
  "Omar",
  "Yasin",
  "Yusuf",
  "Zainab",
] as const;

export const COMMON_MULTICULTURAL_NAMES_SOMALI = [
  "Abdi",
  "Abdullahi",
  "Ayan",
  "Farah",
  "Hodan",
  "Ibrahim",
  "Ifrah",
  "Ilhan",
  "Ismail",
  "Khadra",
  "Nimco",
  "Safiya",
] as const;

export const COMMON_MULTICULTURAL_NAMES_FINNISH = [
  "Aino",
  "Eero",
  "Eino",
  "Emmi",
  "Iida",
  "Juhani",
  "Kaisa",
  "Noora",
  "Onni",
  "Sari",
  "Tuomas",
  "Veeti",
] as const;

export const COMMON_MULTICULTURAL_NAMES_OTHER = [
  "Anastasia",
  "Elena",
  "Ivan",
  "Lejla",
  "Maja",
  "Mila",
  "Milos",
  "Nadia",
  "Nikolai",
  "Sofia",
  "Zara",
] as const;

export const ALL_SWEDISH_NAMES = Array.from(
  new Set([
    ...COMMON_SWEDISH_NAMES_MASCULINE,
    ...COMMON_SWEDISH_NAMES_FEMININE,
    ...COMMON_SWEDISH_NAMES_NEUTRAL,
    ...COMMON_MULTICULTURAL_NAMES_ARABIC,
    ...COMMON_MULTICULTURAL_NAMES_SOMALI,
    ...COMMON_MULTICULTURAL_NAMES_FINNISH,
    ...COMMON_MULTICULTURAL_NAMES_OTHER,
  ]),
);

export function escapeRegex(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
